apiVersion: v1
kind: Pod
metadata:
  name: busybox-pe-1
  labels:
    test: port-exhaust-1
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: kube-ee1
