apiVersion: v1
kind: Pod
metadata:
  name: mt-busybox
  labels:
    test: mt-snatpolicy
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: mt-busybox
  restartPolicy: Always
