apiVersion: v1
kind: Pod
metadata:
  name: busybox-shared
  labels:
    test: busybox-shared-svc-client
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
