apiVersion: v1
kind: Pod
metadata:
  name: case26-ns-busybox
  namespace: case26-ns
  labels:
    test: case26-label
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: case26-ns-busybox
  restartPolicy: Always
