apiVersion: v1
kind: Pod
metadata:
  name: case8-ns-busybox-1
  labels:
    test: pol1
  namespace: case8-ns
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
