apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: case3-nginx-deployment
  labels:
    app: nginx
  namespace: case3-ns
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: case3-nginx
        image: krvikash/nginx-with-utils:v1
        ports:
        - containerPort: 80
