apiVersion: v1
kind: Pod
metadata:
  name: case7-ns-busybox
  namespace: case7-ns
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: case7-ns-busybox
  restartPolicy: Always
