apiVersion: v1
kind: Pod
metadata:
  name: case25-nginx
  namespace: case25-ns
  labels:
    test: case25-label
spec:
  containers:
  - name: case25-ns-nginx
    image: krvikash/nginx-with-utils:v1
    ports:
    - containerPort: 80
