apiVersion: v1
kind: Service
metadata:
  name: case28-nginx-svc-1
  namespace: case28-ns
spec:
  selector:
    app: nginx-1
  ports:
    - protocol: TCP
      port: 9995
      targetPort: 80
  type: LoadBalancer
