apiVersion: v1
kind: Service
metadata:
  name: case4-nginx-service
  labels:
    test: case4-policy
  namespace: default
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9995
      targetPort: 80
  type: LoadBalancer
