apiVersion: v1
kind: Pod
metadata:
  name: case25-ns-busybox
  namespace: case25-ns
  labels:
    test: case25-label
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: case25-ns-busybox
  restartPolicy: Always
