apiVersion: v1
kind: Pod
metadata:
  name: case12-ns-busybox
  namespace: case12-ns
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: case12-ns-busybox
  restartPolicy: Always
