apiVersion: v1
kind: Service
metadata:
  name: case3-nginx-service
  namespace: case3-ns
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9995
      targetPort: 80
  type: LoadBalancer
