apiVersion: v1
kind: Pod
metadata:
  name: case5-ns-busybox
  namespace: case5-ns
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: case5-ns-busybox
  restartPolicy: Always
