apiVersion: v1
kind: Pod
metadata:
  name: case26-nginx
  namespace: case26-ns
  labels:
    test: case26-label
spec:
  containers:
  - name: case26-ns-nginx
    image: krvikash/nginx-with-utils:v1
    ports:
    - containerPort: 80
