apiVersion: v1
kind: Pod
metadata:
  name: case29-busybox
  labels:
    test: case29-snatpolicy
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
