apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
      test: sample-svc-snatpolicy
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9995
      targetPort: 80
  type: LoadBalancer
