apiVersion: v1
kind: Service
metadata:
  name: sample-nginx-service
  namespace: test-ns
spec:
  selector:
    app: nginx1
  ports:
    - protocol: TCP
      port: 9995
      targetPort: 80
  type: LoadBalancer
